---
- name: Add openjdk repository
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: Create user for build packages
  user:
    name: builder
    comment: User for build  packages
    create_home: True
    shell: /bin/bash
    groups: sudo

- name: Install required packages for build
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - wget
    - git
    - build-essential
    - dh-make
    - devscripts
    - software-properties-common
    - python-setuptools
    - unzip
    - openjdk-8-jdk
    - python-pip
    - xz-utils


- name: Install required pip packages (Make sure your managed systems have a valid CA)
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1

